"""
Generates docs/index.html — a shareable static product page for GitHub Pages.
Run: python export_page.py
"""

import json
from pathlib import Path
from src.db import init_db, get_all

DOCS = Path(__file__).parent / "docs"
DOCS.mkdir(exist_ok=True)

def build():
    init_db()
    products = [p for p in get_all() if p["status"] == "ready_for_video"]

    rows_data = []
    for p in products:
        rows_data.append({
            "name":          p.get("name") or p["asin"],
            "category":      p.get("category") or "—",
            "rating":        round(p.get("rating") or 0, 1),
            "price":         round(p.get("price_usd") or 0, 2),
            "reviews":       p.get("review_count") or 0,
            "ships_israel":  bool(p.get("ships_to_israel")),
            "link":          p.get("affiliate_link") or f"https://www.amazon.com/dp/{p['asin']}/",
        })

    products_json = json.dumps(rows_data, ensure_ascii=False)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Winning Products — Affiliation</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css">
  <style>
    body {{ background: #f0f2f5; font-family: 'Segoe UI', sans-serif; }}
    .hero {{ background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); color: #fff; padding: 48px 24px 36px; text-align: center; }}
    .hero h1 {{ font-weight: 800; font-size: 2rem; letter-spacing: -0.5px; }}
    .hero p {{ color: #adb5bd; margin-bottom: 0; }}
    .badge-rating {{ background: #fff3cd; color: #856404; font-weight: 600; }}
    .badge-ship {{ background: #d1e7dd; color: #0a3622; }}
    .card {{ border: none; border-radius: 14px; box-shadow: 0 1px 6px rgba(0,0,0,.08); }}
    .link-btn {{ font-size: .8rem; }}
    .product-name {{ max-width: 320px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; display: inline-block; }}
    .stat {{ text-align: center; }}
    .stat-num {{ font-size: 1.8rem; font-weight: 700; }}
    footer {{ color: #adb5bd; font-size: .8rem; text-align: center; padding: 32px 0; }}
  </style>
</head>
<body>

<div class="hero">
  <h1>🔗 Winning Products</h1>
  <p>{len(products)} products · Ship to Israel · Under $75 · Rated 4.0+</p>
</div>

<div class="container py-4">
  <div class="row g-3 mb-4 justify-content-center">
    <div class="col-6 col-sm-3 stat">
      <div class="card p-3">
        <div class="text-muted small">Products</div>
        <div class="stat-num text-primary">{len(products)}</div>
      </div>
    </div>
    <div class="col-6 col-sm-3 stat">
      <div class="card p-3">
        <div class="text-muted small">Avg Rating</div>
        <div class="stat-num text-warning">
          {round(sum(p["rating"] for p in rows_data if p["rating"]) / max(len(rows_data), 1), 1)} ★
        </div>
      </div>
    </div>
    <div class="col-6 col-sm-3 stat">
      <div class="card p-3">
        <div class="text-muted small">Max Price</div>
        <div class="stat-num text-success">$75</div>
      </div>
    </div>
    <div class="col-6 col-sm-3 stat">
      <div class="card p-3">
        <div class="text-muted small">Ships to</div>
        <div class="stat-num">🇮🇱</div>
      </div>
    </div>
  </div>

  <div class="card p-3 p-md-4">
    <table id="products-table" class="table table-hover table-sm w-100">
      <thead class="table-dark">
        <tr>
          <th>#</th>
          <th>Product</th>
          <th>Category</th>
          <th>Rating</th>
          <th>Price</th>
          <th>Reviews</th>
          <th>Link</th>
        </tr>
      </thead>
      <tbody id="tbody"></tbody>
    </table>
  </div>
</div>

<footer>Generated by Affiliation Pipeline · Products sourced from Amazon Best Sellers</footer>

<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<script>
const products = {products_json};

const tbody = document.getElementById('tbody');
products.forEach((p, i) => {{
  const tr = document.createElement('tr');
  tr.innerHTML = `
    <td class="text-muted small">${{i+1}}</td>
    <td><span class="product-name" title="${{p.name}}">${{p.name}}</span></td>
    <td><span class="badge bg-secondary">${{p.category}}</span></td>
    <td><span class="badge badge-rating">${{p.rating.toFixed(1)}} ★</span></td>
    <td class="fw-semibold">$${{p.price.toFixed(2)}}</td>
    <td class="text-muted small">${{p.reviews.toLocaleString()}}</td>
    <td><a href="${{p.link}}" target="_blank" rel="noopener" class="btn btn-sm btn-outline-primary link-btn">Open ↗</a></td>
  `;
  tbody.appendChild(tr);
}});

$('#products-table').DataTable({{
  pageLength: 25,
  order: [[3, 'desc']],
  columnDefs: [{{ orderable: false, targets: 6 }}],
  language: {{ search: 'Search:' }}
}});
</script>
</body>
</html>"""

    out = DOCS / "index.html"
    out.write_text(html, encoding="utf-8")
    print(f"Generated docs/index.html with {len(products)} products.")

if __name__ == "__main__":
    build()
